version: '3'
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:80
  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: